# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descri\xe7\xe3o')),
                ('date_start', models.DateTimeField(verbose_name='Data de in\xedcio')),
                ('date_finish', models.DateTimeField(verbose_name='Data de t\xe9rmino')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Edi\xe7\xe3o',
                'verbose_name_plural': 'Edi\xe7\xf5es',
            },
        ),
    ]
