# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editions',
            name='participants',
            field=models.ManyToManyField(blank=True, to='participants.Participants'),
        ),
        migrations.AlterField(
            model_name='editions',
            name='edition',
            field=models.IntegerField(verbose_name='Edi\xe7\xe3o'),
        ),
    ]
