# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0002_auto_20160316_0359'),
        ('editions', '0002_auto_20160316_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_finish', models.DateTimeField(verbose_name='Data de t\xe9rmino')),
                ('status', models.BooleanField(default=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editions.Editions')),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant1', to='participants.Participants')),
                ('participant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant2', to='participants.Participants')),
            ],
            options={
                'verbose_name': 'Pared\xe3o',
                'verbose_name_plural': 'Pared\xf5es',
            },
        ),
    ]
