# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_auto_20160316_0359'),
        ('walls', '0002_auto_20160316_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='walls',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do in\xedcio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walls',
            name='participants',
            field=models.ManyToManyField(to='participants.Participants'),
        ),
    ]
