# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0002_auto_20160316_0359'),
        ('walls', '0003_auto_20160316_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vote', models.DateTimeField(auto_now_add=True, verbose_name='Data do voto')),
                ('status', models.BooleanField(default=True)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Participants')),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walls.Walls')),
            ],
            options={
                'verbose_name': 'Vota\xe7\xe3o',
                'verbose_name_plural': 'Vota\xe7\xf5es',
            },
        ),
    ]
