# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 01:49
from __future__ import unicode_literals

import bbb.participants.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('codename', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descri\xe7\xe3o')),
                ('image', models.ImageField(max_length=255, storage=django.core.files.storage.FileSystemStorage(location=b'/Users/carlossa/Documents/Projetos/globo-com/code_challenge_globocom/media'), upload_to=bbb.participants.models.get_upload_to)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
