# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
    ]
